#!/usr/bin/env bash
# Bootstrap the agentic SDLC harness into a target repository.
#
# Usage: ./install.sh /path/to/target-repo
#
# Copies this repository's .claude directory (the harness: agent definitions,
# skills, recipes, scripts, hooks, config, templates) and the thin CLAUDE.md
# core into the target repository root. The harness installs verbatim and is
# never edited per project: the whole of the per-project coupling is
# sdlc.config.yaml, generated by the setup skill after installation.
#
# After running, open Claude Code in the target repository (restart the session
# if it was already open, so the agents and skills register) and run /setup.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 /path/to/target-repo" >&2
  exit 1
fi

TARGET="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="$SCRIPT_DIR/.claude"

if [ ! -d "$TARGET" ]; then
  echo "Error: target directory does not exist: $TARGET" >&2
  exit 1
fi

if [ ! -d "$SOURCE" ]; then
  echo "Error: harness .claude not found at: $SOURCE" >&2
  exit 1
fi

mkdir -p "$TARGET/.claude"
cp -R "$SOURCE/." "$TARGET/.claude/"

if [ -f "$TARGET/CLAUDE.md" ]; then
  echo "Note: $TARGET/CLAUDE.md already exists and was left untouched."
  echo "      The thin core this harness expects is this repository's CLAUDE.md;"
  echo "      merge its 'two roles', 'always-on rules', and 'loading rule'"
  echo "      sections into the existing file."
else
  cp "$SCRIPT_DIR/CLAUDE.md" "$TARGET/CLAUDE.md"
fi

echo "Agentic SDLC harness copied into: $TARGET/.claude"
echo
echo "Next steps:"
echo "  1. Open Claude Code in $TARGET (restart the session if it was already open)."
echo "  2. Run the setup skill (/setup): the interview or brownfield survey writes"
echo "     sdlc.config.yaml, scaffolds the shared memory, and generates the agent registry."
echo "  3. State what you need in plain language; the concierge classifies the intent"
echo "     and the orchestrator composes the run. Or drive one skill at a time by hand."
