# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Generate the agent registry by scanning manifest frontmatter.

The agent registry is the catalogue of every agent role, materialised at
<artefact-root>/agent-registry.md and never hand-edited: adding an agent role to
the catalogue is nothing more than writing its file. The scan reads both
`.claude/agents/` (subagent definitions) and `.claude/skills/` (skill-realised
agent roles), normalising the one key that differs between the two native
layouts (`tools` versus `allowed-tools`). Harness-core skills (intake,
orchestration, prime, setup) declare `scope: harness-core` and are excluded:
the concierge and the orchestrator are not catalogue entries, because the
orchestrator discovering itself would be circular.

The registry is the orchestrator's discovery surface: which agent roles exist,
what each consumes and produces, and whether each is core or bespoke. The
registry says what exists; the availability switch in sdlc.config.yaml says
what this project runs.

Usage:
  uv run .claude/scripts/generate_agent_registry.py [--root .] [--check]

  --check  Exit 1 when the file on disk differs from the scan (drift check);
           writes nothing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

FRONTMATTER_PATTERN: re.Pattern[str] = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)

HARNESS_CORE_SCOPES: frozenset[str] = frozenset({"harness-core"})

MANIFEST_FIELDS: tuple[str, ...] = (
    "inputs",
    "outputs",
    "preconditions",
    "intents",
    "scope",
    "model_floor",
    "cost_tier",
    "standalone",
    "idempotency",
    "primitive",
    "phase",
)


def parse_frontmatter(path: Path) -> dict | None:
    text: str = path.read_text(encoding="utf-8")
    match: re.Match[str] | None = FRONTMATTER_PATTERN.match(text)
    if match is None:
        return None
    try:
        loaded = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        print(f"warning: {path}: frontmatter is not valid YAML: {exc}", file=sys.stderr)
        return None
    if not isinstance(loaded, dict):
        return None
    return loaded


def normalise_tools(manifest: dict) -> str:
    raw = manifest.get("tools") or manifest.get("allowed-tools") or ""
    if isinstance(raw, list):
        joined: str = ", ".join(str(tool) for tool in raw)
        return joined
    return str(raw)


def summarise_io(entries: object, key: str) -> str:
    """One line per declared input or output: name/type plus required marker."""
    if not isinstance(entries, list):
        return "not declared"
    lines: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        if key == "inputs":
            name: str = str(entry.get("name", "?"))
            required_raw: str = str(entry.get("required", "")).lower()
            marker: str = " (required)" if required_raw.startswith(("true", "yes")) else ""
            lines.append(f"{name}{marker}")
        else:
            type_name: str = str(entry.get("type", "?"))
            location: str = str(entry.get("location", ""))
            lines.append(f"{type_name} -> {location}" if location else type_name)
    if not lines:
        return "not declared"
    joined: str = "; ".join(lines)
    return joined


def scan_role_files(claude_dir: Path) -> list[tuple[Path, dict]]:
    role_files: list[tuple[Path, dict]] = []
    agents_dir: Path = claude_dir / "agents"
    skills_dir: Path = claude_dir / "skills"
    candidates: list[Path] = []
    if agents_dir.is_dir():
        candidates.extend(sorted(agents_dir.rglob("*.md")))
    if skills_dir.is_dir():
        candidates.extend(sorted(skills_dir.rglob("SKILL.md")))
    for path in candidates:
        manifest: dict | None = parse_frontmatter(path)
        if manifest is None:
            print(f"warning: {path}: no parseable frontmatter, skipped", file=sys.stderr)
            continue
        scope: str = str(manifest.get("scope", ""))
        if scope in HARNESS_CORE_SCOPES:
            continue
        role_files.append((path, manifest))
    return role_files


def render_registry(role_files: list[tuple[Path, dict]], repo_root: Path) -> str:
    lines: list[str] = [
        "# Agent registry",
        "",
        "Generated by `.claude/scripts/generate_agent_registry.py` scanning the",
        "manifest frontmatter under `.claude/agents/` and `.claude/skills/`.",
        "Never hand-edited: adding an agent role to the catalogue is nothing more",
        "than writing its file and re-running the scan. The registry says what",
        "exists; the availability switch in `sdlc.config.yaml` says what this",
        "project runs; the orchestrator reads both at plan composition.",
        "",
    ]
    for path, manifest in role_files:
        name: str = str(manifest.get("name", path.stem))
        relative: str = str(path.relative_to(repo_root))
        description: str = str(manifest.get("description", "")).strip()
        primitive: str = str(manifest.get("primitive", "subagent")).split(" ")[0]
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- **File:** `{relative}`")
        lines.append(f"- **Primitive:** {primitive}")
        lines.append(f"- **Model:** {manifest.get('model', 'session default')}")
        lines.append(f"- **Tools:** {normalise_tools(manifest)}")
        for field in MANIFEST_FIELDS:
            if field in ("inputs", "outputs", "primitive"):
                continue
            value = manifest.get(field)
            if value is None:
                continue
            rendered: str = str(value).strip()
            lines.append(f"- **{field.replace('_', ' ').capitalize()}:** {rendered}")
        lines.append(f"- **Consumes:** {summarise_io(manifest.get('inputs'), 'inputs')}")
        lines.append(f"- **Produces:** {summarise_io(manifest.get('outputs'), 'outputs')}")
        lines.append("")
        if description:
            lines.append(description)
            lines.append("")
    rendered_text: str = "\n".join(lines).rstrip() + "\n"
    return rendered_text


def resolve_artefact_root(repo_root: Path) -> str:
    config_path: Path = repo_root / "sdlc.config.yaml"
    if config_path.exists():
        try:
            loaded: dict = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
            tree: dict = loaded.get("artefact_tree") or {}
            candidate = tree.get("root")
            if isinstance(candidate, str) and candidate:
                return candidate.rstrip("/")
        except yaml.YAMLError:
            pass
    return "ai_docs"


def main(argv: list[str] | None = None) -> int:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        prog="generate_agent_registry.py",
        description="Scan manifest frontmatter and materialise the agent registry.",
    )
    parser.add_argument("--root", default=".", help="Repository root.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 when the registry on disk differs from the scan; write nothing.",
    )
    args: argparse.Namespace = parser.parse_args(argv)

    repo_root: Path = Path(args.root).resolve()
    claude_dir: Path = repo_root / ".claude"
    role_files: list[tuple[Path, dict]] = scan_role_files(claude_dir)
    rendered: str = render_registry(role_files, repo_root)

    artefact_root: str = resolve_artefact_root(repo_root)
    registry_path: Path = repo_root / artefact_root / "agent-registry.md"

    if args.check:
        on_disk: str = registry_path.read_text(encoding="utf-8") if registry_path.exists() else ""
        if on_disk != rendered:
            print(f"drift: {registry_path} differs from the manifest scan", file=sys.stderr)
            return 1
        print(f"clean: {registry_path} matches the manifest scan ({len(role_files)} roles)")
        return 0

    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {registry_path} ({len(role_files)} agent roles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
